// <auto-generated />
namespace Strek4Mayor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Strek4MayorContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Strek4MayorContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201605170750429_Strek4MayorContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
